#!/bin/bash
echo '
##Bash Shortcuts:
```
$old_command (what does new_command do?)
```
$new_command
```

###Git Shortcuts:
------------------
```
$git add -A
$git commit -m "added this feature"
$git push some_branch
```
```
$ph "added this feature" some_branch
```
------------------
```
$git pull some_branch
```
```
$pll some_branch
```
------------------
```
$git branch some_branch
```
```
$b some_branch
```
------------------
```
$git commit -m "added this feature"
```
```
$cm "added this feature"
```
------------------
```
$git checkout some_branch
```
```
$co some_branch 
```
------------------
```
$git branch some_branch
$git checkout some_branch
```
```
$bco some_branch
```
------------------
```
$git merge some_branch
```
```
$mg some_branch
```
------------------
```
$git log
```
```
$lg
```
------------------
```
$git push origin some_branch
```
```
$pho some_branch
```
------------------
```
$git push origin some_branch
```
```
$pllo some_branch
```
------------------

###Rails Shortcuts
------------------
```
$rake db:create
```
```
$new_db
```
------------------
```
$rake db:drop
```
```
$drop_db
```
------------------
```
rake db:drop
rake db:create
rake db:migrate
```
```
$reset_db
```
------------------
```
rake db:migrate
```
```
$migrate
```
------------------
```
$rails generate ...
```
```
$rg ...
```
------------------
```
$rails generate model ...
```
```
$rgmod ...
```
------------------
```
$rails generate migration ...
```
```
$rgmig ...
```
------------------
```
$rails generate controller ...
```
```
$rgcon ...
```
------------------

###Heroku Shortcuts
------------------
```
$git push heroku master
```
```
$hph
```
------------------
```
$heroku run ...
```
```
$hr ...
```
------------------
```
$heroku logs
```
```
$hl
```
------------------
'